service: serverless-nodejs

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 10
  region: ${self:custom.environment.region}
  memorySize: ${self:custom.environment.memorySize}
  apiKeys:
    - serverless-nodejs-${opt:stage}

custom:
  environment: ${file(./config.json):${opt:stage}}
  stackName: ${self:service}-${opt:stage}  

package:
  exclude:
    - node_modules/**
    - '*.json'
    - '*.yml'
    - test/**
  individually: true  

functions:
  publicApiHandler:
    handler: functions/apis/publicApi.handler
    events:
      - http: 
          path: public
          method: get

  privateApiHandler:
    handler: functions/apis/privateApi.handler
    events:
      - http: 
          path: private
          method: get 
          private: true

  uuidLayerHandler:
    handler: functions/apis/uuidLayer.handler
    events:
      - http: 
          path: public-uuid-layer
          method: get
    layers:
      - !Ref UuidLambdaLayer

layers:
  uuid:
    path: layers/uuid
    name: ${sls:stage}-uuid-layer
    description: generate uuid
    compatibleRuntimes:
      - nodejs14.x
    compatibleArchitectures:
      - x86_64
    retain: false                   
