service: serverless-nodejs

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 10
  region: ${self:custom.environment.region}
  memorySize: ${self:custom.environment.memorySize}
  apiKeys:
    - serverless-nodejs-${opt:stage}

custom:
  environment: ${file(./config.json):${opt:stage}}
  stackName: ${self:service}-${opt:stage}    

functions:
  publicApiHandler:
    handler: functions/apis/publicApi.handler
    events:
      - http: 
          path: public
          method: get

  privateApiHandler:
    handler: functions/apis/privateApi.handler
    events:
      - http: 
          path: private
          method: get 
          private: true
